/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PregnancyRouteImport } from './routes/pregnancy'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BloomAiRouteImport } from './routes/bloom-ai'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminDemosRouteImport } from './routes/admin/demos'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PregnancyRoute = PregnancyRouteImport.update({
  id: '/pregnancy',
  path: '/pregnancy',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BloomAiRoute = BloomAiRouteImport.update({
  id: '/bloom-ai',
  path: '/bloom-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemosRoute = AdminDemosRouteImport.update({
  id: '/admin/demos',
  path: '/admin/demos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/bloom-ai': typeof BloomAiRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/doctors': typeof DoctorsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/pregnancy': typeof PregnancyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/subscription': typeof SubscriptionRoute
  '/symptoms': typeof SymptomsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/demos': typeof AdminDemosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/bloom-ai': typeof BloomAiRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/doctors': typeof DoctorsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/pregnancy': typeof PregnancyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/subscription': typeof SubscriptionRoute
  '/symptoms': typeof SymptomsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/demos': typeof AdminDemosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/bloom-ai': typeof BloomAiRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/doctors': typeof DoctorsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/pregnancy': typeof PregnancyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/subscription': typeof SubscriptionRoute
  '/symptoms': typeof SymptomsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/demos': typeof AdminDemosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/bloom-ai'
    | '/calendar'
    | '/community'
    | '/dashboard'
    | '/demo'
    | '/doctors'
    | '/insights'
    | '/login'
    | '/pregnancy'
    | '/profile'
    | '/register'
    | '/reminders'
    | '/subscription'
    | '/symptoms'
    | '/admin'
    | '/admin/login'
    | '/admin/users'
    | '/admin/content'
    | '/admin/subscriptions'
    | '/admin/analytics'
    | '/admin/settings'
    | '/admin/demos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/bloom-ai'
    | '/calendar'
    | '/community'
    | '/dashboard'
    | '/demo'
    | '/doctors'
    | '/insights'
    | '/login'
    | '/pregnancy'
    | '/profile'
    | '/register'
    | '/reminders'
    | '/subscription'
    | '/symptoms'
    | '/admin'
    | '/admin/login'
    | '/admin/users'
    | '/admin/content'
    | '/admin/subscriptions'
    | '/admin/analytics'
    | '/admin/settings'
    | '/admin/demos'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/bloom-ai'
    | '/calendar'
    | '/community'
    | '/dashboard'
    | '/demo'
    | '/doctors'
    | '/insights'
    | '/login'
    | '/pregnancy'
    | '/profile'
    | '/register'
    | '/reminders'
    | '/subscription'
    | '/symptoms'
    | '/admin/'
    | '/admin/login'
    | '/admin/users'
    | '/admin/content'
    | '/admin/subscriptions'
    | '/admin/analytics'
    | '/admin/settings'
    | '/admin/demos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRoute
  BloomAiRoute: typeof BloomAiRoute
  CalendarRoute: typeof CalendarRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  DoctorsRoute: typeof DoctorsRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  PregnancyRoute: typeof PregnancyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RemindersRoute: typeof RemindersRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SymptomsRoute: typeof SymptomsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminDemosRoute: typeof AdminDemosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregnancy': {
      id: '/pregnancy'
      path: '/pregnancy'
      fullPath: '/pregnancy'
      preLoaderRoute: typeof PregnancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloom-ai': {
      id: '/bloom-ai'
      path: '/bloom-ai'
      fullPath: '/bloom-ai'
      preLoaderRoute: typeof BloomAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demos': {
      id: '/admin/demos'
      path: '/admin/demos'
      fullPath: '/admin/demos'
      preLoaderRoute: typeof AdminDemosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRoute,
  BloomAiRoute: BloomAiRoute,
  CalendarRoute: CalendarRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  DoctorsRoute: DoctorsRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  PregnancyRoute: PregnancyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RemindersRoute: RemindersRoute,
  SubscriptionRoute: SubscriptionRoute,
  SymptomsRoute: SymptomsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminContentRoute: AdminContentRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminDemosRoute: AdminDemosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
