/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PregnancyRouteImport } from './routes/pregnancy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GuideGrossesseRouteImport } from './routes/guide-grossesse'
import { Route as GuideFertiliteRouteImport } from './routes/guide-fertilite'
import { Route as GuideCycleRouteImport } from './routes/guide-cycle'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BloomAiRouteImport } from './routes/bloom-ai'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DoctorDoctorIdRouteImport } from './routes/doctor.$doctorId'
import { Route as DiscussionDiscussionIdRouteImport } from './routes/discussion.$discussionId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDemosRouteImport } from './routes/admin/demos'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AuthenticatedSymptomsRouteImport } from './routes/_authenticated/symptoms'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PregnancyRoute = PregnancyRouteImport.update({
  id: '/pregnancy',
  path: '/pregnancy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideGrossesseRoute = GuideGrossesseRouteImport.update({
  id: '/guide-grossesse',
  path: '/guide-grossesse',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideFertiliteRoute = GuideFertiliteRouteImport.update({
  id: '/guide-fertilite',
  path: '/guide-fertilite',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideCycleRoute = GuideCycleRouteImport.update({
  id: '/guide-cycle',
  path: '/guide-cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BloomAiRoute = BloomAiRouteImport.update({
  id: '/bloom-ai',
  path: '/bloom-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDoctorIdRoute = DoctorDoctorIdRouteImport.update({
  id: '/doctor/$doctorId',
  path: '/doctor/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionDiscussionIdRoute = DiscussionDiscussionIdRouteImport.update({
  id: '/discussion/$discussionId',
  path: '/discussion/$discussionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemosRoute = AdminDemosRouteImport.update({
  id: '/admin/demos',
  path: '/admin/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSymptomsRoute = AuthenticatedSymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/bloom-ai': typeof BloomAiRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/disclaimer': typeof DisclaimerRoute
  '/doctors': typeof DoctorsRoute
  '/faq': typeof FaqRoute
  '/guide-cycle': typeof GuideCycleRoute
  '/guide-fertilite': typeof GuideFertiliteRoute
  '/guide-grossesse': typeof GuideGrossesseRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/pregnancy': typeof PregnancyRoute
  '/privacy': typeof PrivacyRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/symptoms': typeof AuthenticatedSymptomsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/discussion/$discussionId': typeof DiscussionDiscussionIdRoute
  '/doctor/$doctorId': typeof DoctorDoctorIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/bloom-ai': typeof BloomAiRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/disclaimer': typeof DisclaimerRoute
  '/doctors': typeof DoctorsRoute
  '/faq': typeof FaqRoute
  '/guide-cycle': typeof GuideCycleRoute
  '/guide-fertilite': typeof GuideFertiliteRoute
  '/guide-grossesse': typeof GuideGrossesseRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/pregnancy': typeof PregnancyRoute
  '/privacy': typeof PrivacyRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/symptoms': typeof AuthenticatedSymptomsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/discussion/$discussionId': typeof DiscussionDiscussionIdRoute
  '/doctor/$doctorId': typeof DoctorDoctorIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/auth': typeof AuthRoute
  '/bloom-ai': typeof BloomAiRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/disclaimer': typeof DisclaimerRoute
  '/doctors': typeof DoctorsRoute
  '/faq': typeof FaqRoute
  '/guide-cycle': typeof GuideCycleRoute
  '/guide-fertilite': typeof GuideFertiliteRoute
  '/guide-grossesse': typeof GuideGrossesseRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/pregnancy': typeof PregnancyRoute
  '/privacy': typeof PrivacyRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/symptoms': typeof AuthenticatedSymptomsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/discussion/$discussionId': typeof DiscussionDiscussionIdRoute
  '/doctor/$doctorId': typeof DoctorDoctorIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/auth'
    | '/bloom-ai'
    | '/community'
    | '/contact'
    | '/demo'
    | '/disclaimer'
    | '/doctors'
    | '/faq'
    | '/guide-cycle'
    | '/guide-fertilite'
    | '/guide-grossesse'
    | '/help'
    | '/insights'
    | '/pregnancy'
    | '/privacy'
    | '/reminders'
    | '/reset-password'
    | '/subscription'
    | '/terms'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/symptoms'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/demos'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/discussion/$discussionId'
    | '/doctor/$doctorId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/auth'
    | '/bloom-ai'
    | '/community'
    | '/contact'
    | '/demo'
    | '/disclaimer'
    | '/doctors'
    | '/faq'
    | '/guide-cycle'
    | '/guide-fertilite'
    | '/guide-grossesse'
    | '/help'
    | '/insights'
    | '/pregnancy'
    | '/privacy'
    | '/reminders'
    | '/reset-password'
    | '/subscription'
    | '/terms'
    | '/calendar'
    | '/dashboard'
    | '/profile'
    | '/symptoms'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/demos'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/discussion/$discussionId'
    | '/doctor/$doctorId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/articles'
    | '/auth'
    | '/bloom-ai'
    | '/community'
    | '/contact'
    | '/demo'
    | '/disclaimer'
    | '/doctors'
    | '/faq'
    | '/guide-cycle'
    | '/guide-fertilite'
    | '/guide-grossesse'
    | '/help'
    | '/insights'
    | '/pregnancy'
    | '/privacy'
    | '/reminders'
    | '/reset-password'
    | '/subscription'
    | '/terms'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/symptoms'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/demos'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/discussion/$discussionId'
    | '/doctor/$doctorId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRoute
  AuthRoute: typeof AuthRoute
  BloomAiRoute: typeof BloomAiRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DoctorsRoute: typeof DoctorsRoute
  FaqRoute: typeof FaqRoute
  GuideCycleRoute: typeof GuideCycleRoute
  GuideFertiliteRoute: typeof GuideFertiliteRoute
  GuideGrossesseRoute: typeof GuideGrossesseRoute
  HelpRoute: typeof HelpRoute
  InsightsRoute: typeof InsightsRoute
  PregnancyRoute: typeof PregnancyRoute
  PrivacyRoute: typeof PrivacyRoute
  RemindersRoute: typeof RemindersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TermsRoute: typeof TermsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDemosRoute: typeof AdminDemosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DiscussionDiscussionIdRoute: typeof DiscussionDiscussionIdRoute
  DoctorDoctorIdRoute: typeof DoctorDoctorIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregnancy': {
      id: '/pregnancy'
      path: '/pregnancy'
      fullPath: '/pregnancy'
      preLoaderRoute: typeof PregnancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-grossesse': {
      id: '/guide-grossesse'
      path: '/guide-grossesse'
      fullPath: '/guide-grossesse'
      preLoaderRoute: typeof GuideGrossesseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-fertilite': {
      id: '/guide-fertilite'
      path: '/guide-fertilite'
      fullPath: '/guide-fertilite'
      preLoaderRoute: typeof GuideFertiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-cycle': {
      id: '/guide-cycle'
      path: '/guide-cycle'
      fullPath: '/guide-cycle'
      preLoaderRoute: typeof GuideCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloom-ai': {
      id: '/bloom-ai'
      path: '/bloom-ai'
      fullPath: '/bloom-ai'
      preLoaderRoute: typeof BloomAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$doctorId': {
      id: '/doctor/$doctorId'
      path: '/doctor/$doctorId'
      fullPath: '/doctor/$doctorId'
      preLoaderRoute: typeof DoctorDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion/$discussionId': {
      id: '/discussion/$discussionId'
      path: '/discussion/$discussionId'
      fullPath: '/discussion/$discussionId'
      preLoaderRoute: typeof DiscussionDiscussionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demos': {
      id: '/admin/demos'
      path: '/admin/demos'
      fullPath: '/admin/demos'
      preLoaderRoute: typeof AdminDemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/symptoms': {
      id: '/_authenticated/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof AuthenticatedSymptomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSymptomsRoute: typeof AuthenticatedSymptomsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSymptomsRoute: AuthenticatedSymptomsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRoute,
  AuthRoute: AuthRoute,
  BloomAiRoute: BloomAiRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DisclaimerRoute: DisclaimerRoute,
  DoctorsRoute: DoctorsRoute,
  FaqRoute: FaqRoute,
  GuideCycleRoute: GuideCycleRoute,
  GuideFertiliteRoute: GuideFertiliteRoute,
  GuideGrossesseRoute: GuideGrossesseRoute,
  HelpRoute: HelpRoute,
  InsightsRoute: InsightsRoute,
  PregnancyRoute: PregnancyRoute,
  PrivacyRoute: PrivacyRoute,
  RemindersRoute: RemindersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SubscriptionRoute: SubscriptionRoute,
  TermsRoute: TermsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDemosRoute: AdminDemosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DiscussionDiscussionIdRoute: DiscussionDiscussionIdRoute,
  DoctorDoctorIdRoute: DoctorDoctorIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
